---
- name: ansible playbook tutorial
  hosts: _dyheo_ec2
  become: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/dyheo-histech.pem"
  pre_tasks:
    - include: /Users/architect/Code/DevOps-Training-Ansible/ansible-common/epel.yml
  roles:
    - role: nginx

