---
- name: ansible playbook tutorial
  hosts: all
  become: true
  tasks:
    - name: libselinux-python install
      yum:
        name: libselinux-python
        state: present

    - name: EPEL repository install
      yum:
        name: epel-release
        state: present

    - name: nginx install
      yum:
        name: nginx
        state: present

    - name: nginx service start and auto start
      service:
        name: nginx
        state: started
        enabled: true

    - name: nginx service start and auto start
      service:
        name: nginx
        state: started
        enabled: true

#    - name: copy test
#      become: false
#      copy:
#        src: copytest.txt
#        dest: ~/copy.txt



