# tasks file for nginx
- name: nginx install
  yum:
    name:
      - nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: nginx.conf template use
  template:
    src: nginx.j2.conf
    dest: /etc/nginx/nginx.conf
    validate: nginx -t -c %s
  notify:
    - nginx reload

- name: nginx group create
  group:
    name: "{{ nginx_group }}"
    system: true

- name: nginx user create
  user:
    name: "{{ nginx_user }}"
    home: /var/lib/nginx
    shell: /sbin/nologin
    groups: "{{ nginx_group }}"
    append: true
    system: true
